theme: jekyll-theme-cayman
title: Bioinformatics Homework 8
https://user-images.githubusercontent.com/81997058/114476490-4e0a6280-9bc8-11eb-981f-bb5c88596079.png
description: Hello! My name is Rachel Leone. I am a Biochemistry, Molecular and Cell Biology major at Penn State Behrend. I have included a picture of a COVID-19 molecule because I would like to do more research on the virus and it's structure.
