theme: jekyll-theme-cayman
title: Bioinformatics Homework 8
description: Hello! My name is Rachel Leone. I am a Biochemistry, Molecular and Cell Biology major at Penn State Behrend. I have included a picture of a COVID-19 molecule because I would like to do more research on the virus and it's structure.
<img width="297" alt="Screen Shot 2021-04-12 at 8 29 26 PM" src="https://user-images.githubusercontent.com/81997058/114479573-ca07a900-9bce-11eb-960d-45ef60e7b9d1.png">
