theme: jekyll-theme-cayman
title: Bioinformatics Homework 8
description: Hello! My name is Rachel Leone. I am a Biochemistry, Molecular and Cell Biology major at Penn State Behrend. I have included a picture of a COVID-19 molecule because I would like to do more research on the virus and it's structure.
![image](Screen Shot 2021-04-12 at 8.29.26 PM.png)
